# Generated by Django 3.1.6 on 2021-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.IntegerField(max_length=32, null=True),
        ),
    ]
