# Generated by Django 3.1.6 on 2021-03-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_auto_20210328_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pub_date',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='pub_date',
        ),
    ]
