# Generated by Django 3.1.6 on 2021-07-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0010_remove_product_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='active',
        ),
    ]
