# Generated by Django 3.1.6 on 2021-02-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='title',
            new_name='name',
        ),
    ]
