# Generated by Django 3.1.6 on 2021-02-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20210215_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='name',
            new_name='title',
        ),
    ]
