# Generated by Django 3.1.6 on 2021-02-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20210215_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='logo',
            new_name='image',
        ),
    ]
