# Generated by Django 3.1.6 on 2021-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20210215_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='MainLogo',
        ),
    ]
