# Generated by Django 3.1.6 on 2021-02-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_information_myaccount_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='about_us_short_cut',
            field=models.TextField(max_length=10000),
        ),
    ]
