# Generated by Django 3.1.6 on 2021-02-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_auto_20210222_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAccount',
        ),
    ]
