# Generated by Django 3.1.6 on 2021-02-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_delete_myaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
