# Generated by Django 3.1.6 on 2021-03-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
